<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tabel_pemeriksa_model extends CI_Model
{

    public $table = 'tabel_pemeriksa';
    public $id = 'id';
    public $pemeriksa = 'pemeriksa_nama';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function json() {
        $this->datatables->select('tabel_pemeriksa.id,nama,nip,pemeriksa_ip,pemeriksa_role');
        $this->datatables->join('tabel_pegawai','tabel_pemeriksa.pemeriksa_ip = tabel_pegawai.ip','left');
        $this->datatables->from('tabel_pemeriksa');
        return $this->datatables->generate();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->pemeriksa, $this->order);
        return $this->db->get($this->table)->result();
    }

    function pemeriksa()
    {
        $this->db->order_by($this->pemeriksa, $this->order);
        return $this->db->get($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('pemeriksa_nip', $q);
	$this->db->or_like('pemeriksa_nama', $q);
	$this->db->or_like('pemeriksa_ip', $q);
	$this->db->or_like('pemeriksa_jabatan', $q);
	$this->db->or_like('pemeriksa_pagol', $q);
	$this->db->or_like('pemeriksa_role', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('pemeriksa_nip', $q);
	$this->db->or_like('pemeriksa_nama', $q);
	$this->db->or_like('pemeriksa_ip', $q);
	$this->db->or_like('pemeriksa_jabatan', $q);
	$this->db->or_like('pemeriksa_pagol', $q);
	$this->db->or_like('pemeriksa_role', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // get pagol
    function getPagol(){
        return $this->db->get('tabel_golongan');
    }

    // get Jabatan
    function getJabatan(){
        return $this->db->get('tabel_jabatan');
    }

}

/* End of file Tabel_pemeriksa_model.php */
/* Location: ./application/models/Tabel_pemeriksa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-19 17:05:10 */
/* http://harviacode.com */
